"""Type stubs for the compiled extension module ``graphed.core.graphed_core``."""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any

ParamValue = int | float | bool | str
Params = dict[str, ParamValue]

class PayloadDescriptor:
    """Reproducibility metadata an External node carries (participates in the structural hash)."""

    def __init__(
        self,
        *,
        kind: str,
        content_hash: str,
        framework: str,
        version: str,
        io_schema: str,
        preprocessing_ref: str | None = ...,
    ) -> None: ...
    @property
    def kind(self) -> str: ...
    @property
    def content_hash(self) -> str: ...
    @property
    def framework(self) -> str: ...
    @property
    def version(self) -> str: ...
    @property
    def io_schema(self) -> str: ...
    @property
    def preprocessing_ref(self) -> str | None: ...

class GraphStore:
    """Thread-safe interned graph store. Structurally identical nodes share one NodeId."""

    def __init__(self) -> None: ...
    def add_source(self, name: str, params: Params | None = ...) -> int: ...
    def add_op(self, name: str, inputs: list[int], params: Params | None = ...) -> int: ...
    def add_reduction(self, name: str, inputs: list[int], params: Params | None = ...) -> int: ...
    def add_external(
        self,
        descriptor: PayloadDescriptor | dict[str, str | None],
        inputs: list[int],
        params: Params | None = ...,
    ) -> int: ...
    # M39: an Exchange boundary. No name — its identity is its scheme ParamMap (`params`) + input.
    def add_exchange(self, inputs: list[int], params: Params | None = ...) -> int: ...
    # M40: a Join boundary. Two inputs [left, right]; identity is its scheme ParamMap (`params`) + inputs.
    def add_join(self, inputs: list[int], params: Params | None = ...) -> int: ...
    def node_count(self) -> int: ...
    def outputs(self) -> list[int]: ...
    # §8.2(i): indexed by the id of the arena this store was reduced FROM; each entry is
    # (reduced node id, member index inside a fused stage | None), or None where DCE dropped it.
    # Empty for a store that did not come out of a reduction.
    def node_map(self) -> list[tuple[int, int | None] | None]: ...
    # opt_level=0 (M6): the 1:1 cone of `outputs` (DCE without the rewrites), marked with them;
    # its node_map sends each kept id to (cone id, None). An id past the store: ValueError.
    def cone(self, *, outputs: Sequence[int]) -> GraphStore: ...
    def to_dot(self) -> str: ...
    # M8 plan serialization: canonical, versioned, byte-identical durable IR form.
    def serialize(self, outputs: Sequence[int] | None = ...) -> bytes: ...
    @staticmethod
    def deserialize(data: bytes) -> GraphStore: ...
    # M9/M10 IR introspection: structured nodes in id order (for inspect + IR-driven execution;
    # stage nodes carry decoded executable "members").
    def nodes(self) -> list[dict[str, Any]]: ...
    # M4 optimizer (DCE + CSE + equality-saturation stage fusion behind RewriteEngine);
    # maximal_fusion opts in to fusing fan-out ops whose consumers all land in one stage (M10).
    def reduce(
        self, *, maximal_fusion: bool = ..., outputs: Sequence[int] | None = ...
    ) -> tuple[GraphStore, dict[str, int]]: ...
    def reduce_incremental(
        self, *, outputs: Sequence[int] | None = ...
    ) -> tuple[GraphStore, dict[str, int]]: ...
    def reduction_report(self, *, outputs: Sequence[int] | None = ...) -> dict[str, int]: ...

class IncrementalReducer:
    """Genuinely incremental reduction (M10): each step canonicalizes only the nodes recorded
    since the last step; total_work() proves per-step work is the delta, never the history."""

    def __init__(self) -> None: ...
    def step(self, store: GraphStore) -> int: ...
    def watermark(self) -> int: ...
    def total_work(self) -> int: ...
    def canonical_count(self) -> int: ...
    def finalize(
        self, store: GraphStore, *, maximal_fusion: bool = ..., outputs: Sequence[int] | None = ...
    ) -> tuple[GraphStore, dict[str, int]]: ...

def version() -> str: ...
